### ISSUE TITLE
milkman.sh has incorrect line endings for Unix

### ISSUE THREAD

**Issue by AnharMiah** [warmuuh/milkman#10]
### Problem:

unable to run the `milkman.sh` script.

### Steps to Replicate:

```
# pull down dist
wget https://github.com/warmuuh/milkman/releases/download/3.2.0/milkman-dist-linux64-bin.zip
# unzip it
unzip milkman-dist-linux64-bin.zip
cd milkman-dist-linux64-bin/
# make milkman.sh executable
chmod +x milkman.sh
# try and run it!
./milkman.sh
```

you get the following error:

```
$ bash: ./milkman.sh: /bin/sh^M: bad interpreter: No such file or directory
```

### WORKAROUND

Replace Windows line ending with Unix line endings and then run:

```
$ sed -i -e 's/\r$//' milkman.sh
$ ./milkman.sh
```

**Comment by davidjeddy** [comment]
This was exactly my problem, and a perfect fix. TY @AnharMiah

**Comment by DarrienG** [comment]
Ironically in doesn't have Windows line endings in the source code. Somewhere in the release process it gets Windows line endings.
