### ISSUE TITLE
getEnvironmentVariable in header value only returns an empty string.

### ISSUE THREAD

**Issue by ianmacl** [warmuuh/milkman#101]
I have the following header:
`Authorization: Bearer {{js:getEnvironmentVariable("access_token")}}`

I have added a pre-request script to toast the value of the environment variable and the expected value gets displayed in the toast.  But the response I get back is a 401 and if I export as curl, the header is just: ` -H 'Authorization: Bearer '`

I also tried:
`Bearer {{js:milkman.getEnvironmentVariable("access_token")}}` but I get the same result.

Am I doing this wrong?  or is this a bug?  Or is it just not supported?

**Comment by warmuuh** [comment]
Try {{access_token}}. This should have worked too but is a detour via
script plugin. I will look into this, why it didn't work.

ianmacl ***@***.***> schrieb am So., 21. März 2021, 13:39:

**Comment by warmuuh** [comment]
fixed it in nightly version, but access is limited to active environment only (no global environment access for now).
you really should use {{<env-variable>}} syntax.

btw, nightly already ships with oauth2-support, you might be interested in this...

**Comment by ianmacl** [comment]
Thanks!  I switched to {{env-variable}}.

I do not currently have a need for oauth2 but it's a cool feature to have.
