### ISSUE TITLE
Slow UI on Linux without prism forceGPU

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#108]
Hi, 

On linux hardware acceleration faild to start.
With `-Dprism.verbose=true` output log show :

```
System GPU doesn't meet the es2 pipe requirement
```

I found a workaround with option ` -Dprism.forceGPU=true` the GPU (intel) is used and the user interface works fine.

**Comment by warmuuh** [comment]
Really appreciate that someone looks into the Linux issues.. thanks. Will add this soonish

**Comment by YoranSys** [comment]
You welcome i made a PR to force GPU on linux startup script.
