### ISSUE TITLE
Missing .dektop file for linux

### ISSUE THREAD

**Issue by pbsds** [warmuuh/milkman#11]
Being able to search for milkman in the gnome overview is nice. You can add a shortcut by creating a .desktop file and install it to either `/usr/share/applications` or `$HOME/.local/share/applications`.

The way i solved it was by unpacking milkman to 
`$HOME/.local/opt` and writing the file shown below to `$HOME/.local/share/applications/Milkman.desktop`:

```
[Desktop Entry]
Name=Milkman
Exec=/home/pbsds/.local/opt/milkman-3.2.0/milkman.sh
Icon=/home/pbsds/.local/opt/milkman-3.2.0/milk-bottle.png
Terminal=false
Type=Application
Keywords=milkman;postman;rest;http;sql;jdbc;java;
```

Results:
![Screenshot from 2019-07-09 14-12-11](https://user-images.githubusercontent.com/140964/60886981-9195a700-a253-11e9-8887-41ae81e752ad.png)

*(i did download the milk-bottle.png image to make this work)*

I don't know whether the .desktop file supports environment variables or not, but adding a script or something to generate this file (to fill in the home path) or at least providing a template .desktop file would be nice.

**Comment by AnharMiah** [comment]
an `install.sh` would be really nice!

**Comment by pbsds** [comment]
Something like this could work:
```sh
#!/bin/sh
BASE_DIR="$(cd "$(dirname "$0")"; pwd)";

mkdir -p $HOME/.local/share/applications

cat <<EOF > $HOME/.local/share/applications/Milkman_test.desktop
[Desktop Entry]
Name=Milkman
Exec=$BASE_DIR/milkman.sh
Icon=$BASE_DIR/milk-bottle.png
Terminal=false
Type=Application
Keywords=milkman;postman;rest;http;sql;jdbc;java;
EOF
```
