### ISSUE TITLE
UX improvment add a colored background on verb/type of request and reponse code 

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#113]
Can we add: 

- a color on background of verb in place of grey to rapidly identify the type of request? 
![image](https://user-images.githubusercontent.com/11197007/120976705-e5c4a100-c772-11eb-892e-883b5e5533af.png)
Something like this: 
![image](https://user-images.githubusercontent.com/11197007/120977496-ae0a2900-c773-11eb-9348-2e5a4de816fa.png)

- a color on background of response code to rapidly identify the status of response?
 
![image](https://user-images.githubusercontent.com/11197007/120977594-ca0dca80-c773-11eb-8ba6-179cc33997e6.png)

Something like: 
- 200 -> 299: green
- 300 -> 399: yellow 
- 400 -> 499: orange
- 500 -> 599: red

**Comment by warmuuh** [comment]
i like the general idea
Two things tho:
* the type of request (GET,POST etc) can be anything as they are defined by plugins, so it can actually also be SQL or CQL etc... but i guess, some could be colorful, some might not
* i wanted to keep the UX minimal and adding colors changes this (UX gets noisy)

maybe i'll add a configuration option or something, lets see, will give this a thought
