### ISSUE TITLE
milkman-script - var and request

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#114]
Hi ,

I want to upload some file to an API, the payload is in base64 and the original file need to be on my desktop. 

With this pre-script
```java
var Paths = Java.type('java.nio.file.Paths');
var Files = Java.type('java.nio.file.Files');
var Base64 = Java.type('java.util.Base64');
var fileContent = Files.readAllBytes(Paths.get("/tmp/facture.pdf"));
milkman.setEnvironmentVariable("payload", Base64.getEncoder().encodeToString(fileContent));
```

and this body :
```json
{
  "filetype" : "pdf",
  "payload_base64" : "{{payload}}"
}
```

The first request fail, the payload var is unset, i think the request body is already made.

- How can we overwrite the request body ? How can we edit mm.request.body.body ?
- Can we force to apply new var value on the body ?

**Comment by warmuuh** [comment]
never had this usecase but there was some caching issue.

protip: you can create a file somewhere (e.g. ~/.milkman-scripts/utilities.js) and put a function in there 
```javascript
function fileBase64(path) {
  var Paths = Java.type('java.nio.file.Paths');
  var Files = Java.type('java.nio.file.Files');
  var Base64 = Java.type('java.util.Base64');
  var fileContent = Files.readAllBytes(Paths.get(path));
  return Base64.getEncoder().encodeToString(fileContent);
}
```

then if you include that file in options -> scripting (using `file:///Users/...` uri) you can use it in your body like:
```json
{
  "filetype" : "pdf",
  "payload_base64" : "{{js:fileBase64('/tmp/facture.pdf')}}"
}
```

and you dont have to store it in environment at all

**Comment by YoranSys** [comment]
Wow impressive :clap: 
thank you
