### ISSUE TITLE
milkman-rest - permit to see the computed output request 

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#115]
For debug purpose and transparency it would be great to view, headers and body of the output request (computed output with variable and after pre-script).

**Comment by warmuuh** [comment]
i normally use an echo service like https://learning.postman.com/docs/developer/echo-api/ for this. i dont want to put any debugging facility in milkman directly though.   do you think, this is enough for you already?

**Comment by YoranSys** [comment]
I don't like to send sensitive information to external service like postman echo and some of my colleague doesn't have the ability to start local echo service. It would be very convenient to have output directly on the UI. 

I just find a workaround with the export option.  There is only one caveat, the before request script is not run before and the curl/http output doesn't reflect the real request. But I don't think it's a good idea to run script on export :sweat_smile: .

**Comment by warmuuh** [comment]
another option would be to use netcat `nc -l localhost 8080` and there you go :D. but i get your point, i think about adding debug output, but on low prio....
