### ISSUE TITLE
Rest path parameters

### ISSUE THREAD

**Issue by zephyrgr** [warmuuh/milkman#127]
Is there any way to configure path parameters?

**Comment by warmuuh** [comment]
you can use parameters as usual, also in url. example:

```
http://some-domain/users/{{userId}}
```
and configure a `userId` environment variable.  (pro-tip:  https://github.com/warmuuh/milkman/blob/master/docs/features.md#quick-edit-for-variables )

**Comment by zephyrgr** [comment]
Thanks for the quick answer. 

I think i found a problem when creating a new variable if there is no environment specified:

![image](https://user-images.githubusercontent.com/88770028/129001043-f9ba4ab4-bac0-4f4a-8c28-d7b4537f5714.png)

Also, is it possible to add these variables per request instead of per environment?

**Comment by warmuuh** [comment]
I don't see much value in having parameters per request, except for documentation purposes but that's not what milkman is for.

Having no environment does result in some buggy situations, that's true... Might have a look into fixing those

**Comment by warmuuh** [comment]
closed in favor of #128
