### ISSUE TITLE
Error when exporting via sharebin

### ISSUE THREAD

**Issue by inqvan** [warmuuh/milkman#129]
![CleanShot 2021-08-31 at 15 14 57](https://user-images.githubusercontent.com/8516045/131500996-9d6dfdd8-ab36-4f3e-a848-a172d42c0797.png)

Hi, thanks for the cool program

When I try to share collection via sherebin I get error: Failed to store requests

The issue is reproduced on different versions and on different collections.

**Comment by warmuuh** [comment]
hi. thanks for the bug report. fix is available in nightly version
