### ISSUE TITLE
Wrong version number in MacOS download release 5.3.0

### ISSUE THREAD

**Issue by suschizu** [warmuuh/milkman#139]
Hello! Just noticed that the MacOS downloads always contain version number 1.0 instead of 5.x.x. (the short version string wasn't updated)
<img width="397" alt="Screenshot 2021-10-18 at 00 22 37" src="https://user-images.githubusercontent.com/16004333/137647127-f07f9247-8bb5-4a94-a7a3-8c0badfd6d41.png">

**Comment by warmuuh** [comment]
wont fix. this conflicts with cross-platform build and i dont want to spend too much time for debugging this
