### ISSUE TITLE
Milkman has small scaling on laptop with 4k display

### ISSUE THREAD

**Issue by pdsimanyi** [warmuuh/milkman#149]
Milkman starts with small fonts and UI elements on a laptop with a 4k display. An attached picture shows this.

Update, workaround: it's possible to scale by setting GDK_SCALE: [GDK_SCALE](https://github.com/warmuuh/milkman/issues/149#issuecomment-1047413512)

The picture shows Milkman in front of a full-height terminal (konsole) in KDE 5.24 on Ubuntu 20.04 on a 15.6" 3840x2160 laptop, with the WM's scaling set to 125%.

Since I suspect changing scaling to follow all the different WM's is on Linux is time-consuming and nonobvious, it'd be great to have any solution at all to scale up the app's UI. Scaling the entire UI by a fixed multiplier would work, and it'd be completely fine to have to manually modify milkman.sh adding `java -D...` or changing any file, or even have some personally-applied fix in the JavaFX code that scales each window. I'm trying to express that this scaling doesn't have to be a clean change to the app with changes to some Settings code, and that any quick-to-implement fix would be great.
![milkman](https://user-images.githubusercontent.com/4816285/154774566-89515e13-c46b-4dc3-8fe3-263ef0299a99.jpg)

**Comment by warmuuh** [comment]
Apparently, javafx has some issues in Ubuntu (see https://unix.stackexchange.com/q/512837)

Can you try this:
```
gsettings set org.gnome.desktop.interface scaling-factor 2
```

Otherwise I'll be looking into a simple scaling feature...

**Comment by pdsimanyi** [comment]
Thanks.

I'm investigating this myself now, because that setting didn't scale up the UI.

I found the code referencing that setting, jfloat getUIScale(GdkScreen* screen) in glass_screen.cpp:
https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/native-glass/gtk/glass_screen.cpp#L106

After reading the code, I'll try setting things that may change the scale. And if that doesn't work, I may try to build the code and manually add logging to a local file showing which code paths are executed. I haven't looked at your code yet to see how easy it is to configure using a locally-built JavaFX version.

Also I'll probably search commits to find possibly relevant ones like
https://github.com/openjdk/jfx/commit/782f22a118b71c86b33b37d13e59b308b3cf7f41

**Comment by pdsimanyi** [comment]
New info, great news: this change to milkman.sh did scale the window up!

```
GDK_SCALE=2 \ 
"$BASE_DIR"/jre-linux64/bin/java -XX:SharedArchiveFile="$BASE_DIR"/app-cds.jsa \ 
\
```

So we have a workaround, and you can decide whether to document this, perhaps change the .sh script to accept scale as a parameter or something. (Knowing this change only changes scale on a very limited set of Unix-like OS's and window managers.) It might be fine to simply put it in a FAQ, or edit this issue's title and anything so the workaround is easy to find.

**Comment by warmuuh** [comment]
thanks for putting that effort in. i'll document it somewhere

**Comment by grinderX19** [comment]
For Windows 10 you might add "-Dsun.java2d.uiScale=1.25" into milkman.bat for scaling to 125%, for example. If not added there are some minor UI issues.
