### ISSUE TITLE
Can't open on Mac due to lack of signature

### ISSUE THREAD

**Issue by exadeci** [warmuuh/milkman#152]
On my professional mac I can't open Milkman as it's not signed and my corporate rules don't allow me to "Open anyway"

<img width="260" alt="Screen Shot 2022-04-07 at 10 35 47 am" src="https://user-images.githubusercontent.com/1394130/162097228-8d147674-ce88-42f6-9ff2-03639c841bbf.png">

**Comment by warmuuh** [comment]
Have you tried control-clicking the app? If it really cannot be opened because of policies, I don't see any option then to make it work. I won't pay for a developer account at Apple so that is not an option, sorry...
