### ISSUE TITLE
JitPack and Spring Repo unauthorized

### ISSUE THREAD

**Issue by pauljackals** [warmuuh/milkman#153]
While building a jar I get an error saying that I'm unauthorized to read your dependencies at `https://jitpack.io` and `http://repo.spring.io/plugins-release`. It seems they have anonymous access disabled.

**Comment by warmuuh** [comment]
i just tried to re-download everything and it all works fine: 
```
Downloading from jitpack.io: https://jitpack.io/com/github/warmuuh/hardwire/0.0.4/hardwire-0.0.4.pom
Downloaded from jitpack.io: https://jitpack.io/com/github/warmuuh/hardwire/0.0.4/hardwire-0.0.4.pom (2.1 kB at 1.3 kB/s)
Downloading from jitpack.io: https://jitpack.io/com/github/warmuuh/hardwire/0.0.4/hardwire-0.0.4.jar
Downloaded from jitpack.io: https://jitpack.io/com/github/warmuuh/hardwire/0.0.4/hardwire-0.0.4.jar (1.9 MB at 1.1 MB/s)
```
(i did not setup anything special for jitpack). i think, the problem might be somewhere else? proxy?

**Comment by pauljackals** [comment]
Right, I checked it a bit more and these work:
```
https://jitpack.io/com/github/warmuuh/milkman/5.4.0/milkman-5.4.0.pom
https://jitpack.io/com/github/warmuuh/milkman/5.4.0/milkman-5.4.0.jar
```
However, here it asks me for credentials:
```
https://jitpack.io/com/github/warmuuh/milkman-rest/5.4.0/milkman-rest-5.4.0.pom
https://jitpack.io/com/github/warmuuh/milkman-rest/5.4.0/milkman-rest-5.4.0.jar
```

**Comment by warmuuh** [comment]
i see, you are developing a plugin. I thought you try to compile milkman itself.

that issue might be because it cant find the repo and thinks, it is a private repo.
this works:
```
https://jitpack.io/com/github/warmuuh/milkman/5.4.0/milkman-rest-5.4.0.jar
```
as this is a multimaven module, the dependency needs to be defined like written [here](https://docs.jitpack.io/building/#multi-module-projects):

```
<dependency> 
    <groupId>com.github.User.Repo</groupId> 
    <artifactId>Module</artifactId> 
    <version>Tag</version> 
</dependency>
```

i'll check the docs of milkman if i can improve them a bit

**Comment by pauljackals** [comment]
Thanks, I've never worked with multi-module maven project, it confused me a bit. However, I still can't access the link you pasted 😅.
For now I've added local maven directory as repository in `pom.xml` as a workaround and it somehow worked after copying files from `~/.m2/repository/com/github/warmuuh/milkman/milkman-rest/5.4.0/` to `~/.m2/repository/com/github/warmuuh/milkman-rest/5.5.0-SNAPSHOT/`.

**Comment by warmuuh** [comment]
hm, thats because i posted the wrong link. this is the right one:
https://jitpack.io/com/github/warmuuh/milkman/milkman-rest/5.4.0/milkman-rest-5.4.0.jar

i updated the docs as well: https://github.com/warmuuh/milkman/blob/master/docs/plugin-development-setup.md

**Comment by pauljackals** [comment]
That did the trick! Before I was only able to build whole project with all modules, but after changing `<groupId>com.github.warmuuh</groupId>` to `<groupId>com.github.warmuuh.milkman</groupId>` in a specific plugin's dependencies, I can build just it, without everything else. Thanks!
