### ISSUE TITLE
response body scripting broken on macos

### ISSUE THREAD

**Issue by elmir-b** [warmuuh/milkman#170]
Hi,

In milkman on MacOS, it's not possible to use scripting with responses in the "AfterRequest" with GRPC. Body is null.

If I use the example from scripting/readme.md I get the following:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/39994587/233329196-70442429-1282-4fdb-8421-e4cf30d61bd6.png">

**Comment by warmuuh** [comment]
unluckily, it is called payload.payload for grpc
see https://github.com/warmuuh/milkman/blob/master/milkman-grpc/src/main/java/milkman/plugin/grpc/domain/GrpcPayloadAspect.java for reference (name of the aspect = "payload", property-name: "payload")
hope, it helps

**Comment by warmuuh** [comment]
yeah, two things: i mixed up request vs response, the right code would be `console.log(JSON.parse(milkman.response.Payload.payloads).url)`, but this didnt work (some regression). i fixed it right now (https://github.com/warmuuh/milkman/commit/1ee9682401860fce6a4639e0aa3376a7899219c2) so nightly version contains the fix (in some minutes).   
(verified the fix locally, so it *should* work :D)

**Comment by warmuuh** [comment]
created follow-up: https://github.com/warmuuh/milkman/issues/171

**Comment by elmir-b** [comment]
Very nice, I also saw it in the other PR.

One thing I would have really liked when I first discovered milkman is more scripting examples in the docs. Other than that great tool and thanks for your work!
