### ISSUE TITLE
Syncing does not import params for different enviornments

### ISSUE THREAD

**Issue by ndrader** [warmuuh/milkman#176]
When setting up a query that utilizes parameters the data for the parameters ends up in the git repo, however it does not pull down to a second user on sync. 

Do see everything else for the queries get pulled in.

Utilizing git sync with ssh and token. 

Version 5.6.0 of Milkman

**Comment by warmuuh** [comment]
to be sure: do you mean the "parameters" tab on http-requests?

**Comment by ndrader** [comment]
yes

**Comment by ndrader** [comment]
Sorry just spoke with coworker, it appears i had the information wrong. Sorry about that. Everything is functioning as expected.
