### ISSUE TITLE
Insomnia Import Support

### ISSUE THREAD

**Issue by WtfJoke** [warmuuh/milkman#181]
https://insomnia.rest/ is a famous alternative to Postman. They recently released a new version, which pushes users to create an account. More can be found here: https://github.com/Kong/insomnia/discussions/6590

So a lot of users (including myself) search for an alternative. I wanted to give milkman a try.

So it would be great if Milkman would have import for Insomnia Exports.

**Comment by warmuuh** [comment]
Oh, interesting 🤔 enshittificaton hits insomnia as well 🤣
Will look into adding an import for insomnia this week if I find time

**Comment by warmuuh** [comment]
Found some time: https://github.com/warmuuh/milkman/blob/master/docs/features.md#insomnia-import
This ist only yet available in the nightly Version though.
A proper release will be coming soon but as there are a lot of changes, i like to see if there are some issues with it before releasing.

**Comment by WtfJoke** [comment]
That was fast, thanks!
