### ISSUE TITLE
 Add a control to automatically wrap the line display

### ISSUE THREAD

**Issue by bjchenshuijun** [warmuuh/milkman#199]
As shown in the image below, when the content is too long, you need to drag the horizontal scroll bar to the right to see the rest of the content. 
Can you add a control to automatically wrap the line display, that is, the original long line of content is automatically changed to multi-line display?
![1713419578043](https://github.com/warmuuh/milkman/assets/53248787/836bb3a7-1e29-45fe-8fe6-8c402925bb6a)

**Comment by warmuuh** [comment]
added softwrap button in nighly
