### ISSUE TITLE
Test with HTTP request "hangs"

### ISSUE THREAD

**Issue by janvlug** [warmuuh/milkman#200]
For me HTTP GET requests in a TEST do not finish. The spinner keeps spinning and the Outcome field in the Results tab states STARTED.

This is what I do:
* create a new HTTP GET request to: https://ddg.gg and save it under as DDG.
* when I submit this DDG-request, it returns and shows a Response Body.
* create a new TEST
* drag the DDG-request into the Tests tab
* click submit
* a spinner starts, but the request seems not to finish

Screenshot while "hanging":
![image](https://github.com/warmuuh/milkman/assets/5903208/12727872-2ff0-49f3-a0cd-c761248d14bc)

**Comment by warmuuh** [comment]
bug got introduced in 5.8.0.   fixed in nightly
