### ISSUE TITLE
How to send a POST with form data?

### ISSUE THREAD

**Issue by msdobrescu** [warmuuh/milkman#32]
Hello,

In Postman, in the body, there is a form-data input.
How could this be done in Milkman?

Thanks.

**Comment by warmuuh** [comment]
there is no special ui support for this.
just set the header to `application/www-x-form-urlencoded` and send parameters in the body like param1=value1&param2=value2

**Comment by msdobrescu** [comment]
It does not work.

**Comment by warmuuh** [comment]
It should, as this is how html forms work. See https://stackoverflow.com/questions/8417224/how-to-mimic-an-html-form-submission-in-a-post-request

The problem might be somewhere else.

**Comment by msdobrescu** [comment]
I understand, but it is something I can't publish.
If I make the same request in Postman, it works. But that uses <key>:<value> entries list.
So, could it be some syntax? What is the exact syntax I should use?

**Comment by warmuuh** [comment]
Depending on the values,you might need to escape them. I feel that proper
support for specific content types does help, I might add it in the future
release. Thanks for pointing out that there is a need for this.

Mihai Sorin Dobrescu <notifications@github.com> schrieb am Sa., 16. Nov.
2019, 10:03:

**Comment by msdobrescu** [comment]
OK, I've got it, I have escaped the contents of the form in the body, but I had to escape the ampersands between them too.

**Comment by msdobrescu** [comment]
My two cents: add a feature for the params list (as you do for the header) and escape the body ampersands between the keys and values entries at post time.

**Comment by commonquail** [comment]
NB: the correct `content-type` header value is `application/x-www-form-urlencoded`. The explanation above has a subtle error.

**Comment by warmuuh** [comment]
thanks for that, adjusted
