### ISSUE TITLE
protoc-jar stuff

### ISSUE THREAD

**Issue by os72** [warmuuh/milkman#37]
Hi there, somehow I noticed your usage of `protoc-jar` (I'm the author)
https://github.com/warmuuh/milkman/commit/5e45f7e507d6d1dd60abfc874addf08c6200386f

Note that an API exists that allows capturing stdout/stderr: `public static int runProtoc(String[] args, OutputStream out, OutputStream err)`

And there is a built-in option to include the well-known types (`--include_std_types`)

Also, I saw something about grpc reflection -- FYI there is a separate project to make life easier with protobuf reflection, check it out perhaps:
https://github.com/os72/protobuf-dynamic

Cheers!

**Comment by warmuuh** [comment]
thanks for those tips. I added the changes accordingly. Are you by any chance aware of any way to convert a FileDescriptorSet (retrieved by reflection from server) into a set of *.proto files? I am doing this manually but i dont quite like that approach

**Comment by os72** [comment]
I'm not aware but yes it would be a nice feature. It's been mentioned before: https://github.com/os72/protobuf-dynamic/issues/7
I haven't spent time on it, but there must be reasons why `toString()` exists, but not some `toProtoString()`..
