### ISSUE TITLE
Feature request: export as OpenAPI draft specification.

### ISSUE THREAD

**Issue by tpoindex** [warmuuh/milkman#50]
First, thanks for Milkman!

A nice-to-have for me is exporting a Collection as an OpenAPI specification.  Obviously there are a few issues that might might need to be resolved, such as providing object names for a request body in JSON format and  response JSON objects.  Without names, these objects would just take the name of the request name.

This would be a big help in developing an OpenAPI specification based on a Milkman test suite, even if a complete specification might need some hand tweaking.

https://swagger.io/specification/

**Comment by warmuuh** [comment]
Sounds useful. I might think of a separate plugin with im/export for openapi...maybe other openapi related features as well...

**Comment by warmuuh** [comment]
hi. i decided against implementing openapi-spec export as it is not directly related to the core functionality of milkman. it should not be a tool to create specs, it should be a tool for debugging / exploring APIs. I did implement an openapi-import though and based on this, you could easily implement an exporter as well, i guess.

**Comment by tpoindex** [comment]
Any verbal description of how to accomplish adding an exporter would appreciated.  That way, I can decided whether to try to add the exporter, or just move on. Thanks.

**Comment by warmuuh** [comment]
sure, all you need to do implement a [collectionExporter](https://github.com/warmuuh/milkman/blob/master/milkman/src/main/java/milkman/ui/plugin/CollectionExporterPlugin.java)(here is the example [postman exporter](https://github.com/warmuuh/milkman/blob/master/milkman-rest/src/main/java/milkman/ui/plugin/rest/postman/PostmanCollectionExporter.java)) and create an [OpenAPI spec](https://github.com/warmuuh/milkman/blob/master/milkman-rest/src/main/java/milkman/ui/plugin/rest/openapi/OpenapiImporterV30.java#L26) and write it to some file.   to create a separate plugin, just create a new project which imports the dependencies as provided (such as for example the [explorer-plugin ](https://github.com/warmuuh/milkman/blob/master/milkman-explore/pom.xml)which depends on rest-plugin). to depend on milkman, you can use jitpack.io as described [here](https://github.com/warmuuh/milkman/blob/master/docs/plugin-development-setup.md), or have both projects in the same workspace.
