### ISSUE TITLE
Support question regarding TLS 1.2 handshake

### ISSUE THREAD

**Issue by brjoha** [warmuuh/milkman#56]
I'm having trouble getting past the TLS handshake to my target, though cURL has no issue.  Milkman under Windows has a pop-up reporting...

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake

...while the target has a log reporting a handshake timeout.

Milkman under Linux has java logs reporting...

07:40:28.769 [JavaFX Application Thread] INFO milkman.ctrl.WorkspaceController - Received response
07:40:28.822 [elastic-2] ERROR milkman.ui.plugin.rest.ResponseBodyTabController - Received Error
java.security.cert.CertificateException: No subject alternative names present

So I'm guessing an alternative name is required in the certificate for Milkman to properly connect?

**Comment by warmuuh** [comment]
just had a look, this seems to happen when you try to connect to a service by using e.g. the ip (https://xx.xx.xx.xx) or for that matter, a different name then in the certificate.  i will have a look to see how to ignore this but for now, you could try to use the right name  ;)

**Comment by brjoha** [comment]
You're right that in the PC case, the address in the URI didn't match the CN in the certificate.  But in the Linux case (same host as the target), it did and still didn't connect :(  I'm trying again in the Linux environment.

**Comment by warmuuh** [comment]
i disabled hostname verification now cause i think, it fits the role of milkman as a debugging tool. give it a try by downloading [the nightly version](https://github.com/warmuuh/milkman/releases/tag/nightly)

**Comment by brjoha** [comment]
Ok, thanks.  I'll give it a try.  I thought the "Validate Certificates" setting controlled this in the environment settings.

**Comment by warmuuh** [comment]
It should but apparently you can only disable this via an internal jdk flag at start of application...
