### ISSUE TITLE
choco install milkman-grpc isn't found

### ISSUE THREAD

**Issue by shawnwildermuth** [warmuuh/milkman#59]
The GRPC plugin page doesn't indicate what the chocolatey name is. 

The output from choco is:

```
[ADMIN]: C:\Program Files\PowerToys> choco install milkman-grpc
Chocolatey v0.10.15
Installing the following packages:
milkman-grpc
By installing you accept licenses for the packages.
milkman-grpc not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - milkman-grpc - milkman-grpc not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```

**Comment by warmuuh** [comment]
i think that is because grpc came after choco was setup. sadly, i have no clue how choco was setup, someone else did this.
@digitalcoyote  maybe  you can be bothered adding the new plugins (i think, grpc and cassandra) to the choco setup?

**Comment by digitalcoyote** [comment]
I'll try to add this in as soon as I get a chance. Might be later this week.

**Comment by shawnwildermuth** [comment]
If I can help, let me know.

**Comment by digitalcoyote** [comment]
[milkman-grpc](https://chocolatey.org/packages/milkman-grpc/4.5.0 ) has been added to chocolatey. I'll make sure to add cassandra and update the milkman-plugins package later. I have them ready, but it appears I've forgotten to push them.

**Comment by shawnwildermuth** [comment]
Awesome!

**Comment by warmuuh** [comment]
Thanks a lot, @digitalcoyote , really appreciated

**Comment by shawnwildermuth** [comment]
Any idea when it will be approved in Chocolatey?

**Comment by digitalcoyote** [comment]
It's done by volunteers. I've seen new packages take upwards of 2 weeks. After they feel they can trust it, they'll mark it and it will bypass manual review.
