### ISSUE TITLE
Support for disabling UI animations?

### ISSUE THREAD

**Issue by pandruszkow** [warmuuh/milkman#62]
Is there any way to disable the animations in the UI (or a plan to support that as a configurable option)?

My situation is a bit unusual, since I'm using X11 forwarding with software graphics rendering (it's the only thing that works with my setup). This means that all animations on every application are very slow and full of artifacts. Being able to disable such animations would make the application nicer to use.

**Comment by warmuuh** [comment]
I had them disabled for a while. Making this configurable sounds usefull anyway, I will as it soonish, good idea

**Comment by warmuuh** [comment]
i disabled every animation that was easily disableable. unfortunately, not all animations can be disabled in the ui-lib in use without dirty hacks...
