### ISSUE TITLE
brew - “Milkman” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by lpicquet** [warmuuh/milkman#77]
“Milkman” cannot be opened because the developer cannot be verified.

![image](https://user-images.githubusercontent.com/2588528/100749599-c7a17100-33dc-11eb-8318-fb0a4561c515.png)

`brew cask install milkman` worked successfully

**Comment by warmuuh** [comment]
i think, you have to go to "Security & Privacy" and "Allow Anyway" milkman. now you can retry and you should have a button "open"
