### ISSUE TITLE
How to install plugins?

### ISSUE THREAD

**Issue by CDRayn** [warmuuh/milkman#79]
I'm trying to install the `milkman-grpc` plugin and I'm not having any luck. So far I've built the plugin's Jar file by running `mvn package` in the plugin's directory. I then move that Jar file into the `plugins` directory of Milkman but when I launch the application I get no indication that the plugin is install and available. The documentation is vague and don't really give much indication about what steps need to be performed.

I'm using Milkman 5.0.0 and running on Kubuntu 20.04 LTS. Any help would be much appreciated. Thank you.

**Comment by warmuuh** [comment]
the grpc-plugin is included in the plugin-artifact in the release. so all you need to do is to download that artifact and extract the jar into the /plugins folder. you are then able to create a new GRPC requests via the `+` on the upper right in milkman.

building it manually and copy it there obviously works as well, so i suppose, you just did not see the new request-type in the `+`-menu.

**Comment by CDRayn** [comment]
@warmuuh This might be a dumb question, but where are the plugin artifacts located? I didn't see anything under the GitHub release section that indicated artifacts for plugins? Also, thank you for your quick response. I really appreciate it and for the effort you put into this project. Thank you.

**Comment by digitalcoyote** [comment]
@CDRayn I think you may be looking for the milkman-dist-plugins-bin.zip for each release under assets. It blends in a bit since it follows the same naming conventions as the is specific archives.

**Comment by CDRayn** [comment]
@digitalcoyote Ah, I see now. While it does blend in a little bit with the rest of the artifacts, I'll admit that is a bit of a face palm moment for me. I just extracted the plugin artifacts and it seems to be working. Please consider this issue resolves. Also, would it be alright if I add a few notes to the documentation about extracting and installing the plugins? I think it might make things a little more clear.

**Comment by warmuuh** [comment]
Please do so, thx
