### ISSUE TITLE
Not able to do gRPC calls when server uses SSL

### ISSUE THREAD

**Issue by joelstahre** [warmuuh/milkman#80]
Hey

Im not able to do gRPC calls to my server.

`domain.com:443`

i get `Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f`

Any help is appriciated!

**Comment by warmuuh** [comment]
If I remember correctly, that is hex for "HTTP"... And shows that you called an http endpoint, not a grpc endpoint. Wrong port?

**Comment by joelstahre** [comment]
Ok, i see, so im not able to do that?
i can do it in BloomRPC for instance

**Comment by warmuuh** [comment]
not sure what BloomRPC does. if you wanna call Http endpoint, use normal request-type, otherwise Grpc. i did not experience any issues with that. i would like to know though what the exact problem is...  btw, the default port for grpc is 9080, have you tried this one?

**Comment by warmuuh** [comment]
i just added support for SSL/TLS for Grpc calls now which can be activated manually (similar to BloomRpc (TLS toggle). this allows you now to call grpc services that use TLS. what you might have referred to is the Grpc-Web standard which you can activate in BloomRpc via the GRPC<->WEB toggle. this is not yet supported in milkman. please let me know, if that is what you ment.

**Comment by warmuuh** [comment]
i'll close this now as fixed, as i added TLS support. if you'd like to see [Grpc-Web](https://github.com/grpc/grpc-web) support, please open a new ticket
