### ISSUE TITLE
Support for HTTP Authentication

### ISSUE THREAD

**Issue by StuTheBearded** [warmuuh/milkman#92]
Currently HTTP authentication is available via manually setting http headers which is fine, but can we have an option to base64 encode the values of the headers as some API's expect this. For example

Header            | Value                               
------------------- | ----------------------------------  
Authorization:  | Basic *base64_encoded*

It might be nice to authentication as general option set

**Comment by warmuuh** [comment]
you can already via script plugin, just set header to
```
Authorization: Basic {{js:base64("name:pw")}}
```
i feel this is enough for such a basic usecase. i do think about adding separate auth-functionality, but up until now, i dont really see a need for this (maybe some oauth support, but there was no need yet for me)

**Comment by StuTheBearded** [comment]
Ah that's good to know, now I have the plug-ins installed that's working correctly.

(off topic, its been a very long time since I've seen that sheep icon)
